// <auto-generated />
namespace PingYourPackage.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TheFinal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TheFinal));
        
        string IMigrationMetadata.Id
        {
            get { return "201403171209360_The Final"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
