// <auto-generated />
namespace PingYourPackage.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class CompleteTheStructure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CompleteTheStructure));
        
        string IMigrationMetadata.Id
        {
            get { return "201403111318457_CompleteTheStructure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
